version: '3'

services: 
  app:
    depends_on:
      - db
    build:
      context: ./node
    container_name: app
    entrypoint: sh -c "dockerize --wait tcp://db:3306 --timeout 20s && npm install && node index.js"   
    volumes:
      - ./node:/usr/src/app
    tty: true
    networks:
      - mynet
    ports:
      - "3000:3000"
    

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: nginx:prod
    container_name: nginx
    networks: 
      - mynet
    ports: 
      - "8080:80"
    depends_on:
      - app

  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always    
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    networks:
      - mynet
  
networks: 
  mynet:
    driver: bridge